version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: true
  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: pytest test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
