version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: python setup.py install
  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: ls
      - run: pytest tests

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
