version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: pip install pytest -r requirements.txt
      - run: python setup.py install
      - run: pytest tests

workflows:
  build_and_test:
    jobs:
      - build_and_test
