version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  # I did not find a way to execute different jobs in the same container
  # so building and testing are done in the same job
  build_and_test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: 
          name: Installing requirements and test modules
          command: pip install pytest-cov -r requirements.txt
      - run: 
          name: Installing module
          command: pip install .
      # - run: pytest tests
      - run:
          name: Code Coverage
          # Explaination:
          # - finds where the repo is installed
          # - runs the test with pytest-cov 
          command: |
            pytest --cov-report xml --cov="$(pip show networkMDE | grep Location | awk '{print $2}')/networkMDE" tests/
      - codecov/upload

workflows:
  build_and_test:
    jobs:
      - build_and_test